name: Generate GitHub Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 UTC 跑一次（台灣早上 8 點）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake files
        uses: Platane/snk@v3
        with:
          github_user_name: seven-317
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            "dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"
            # ↑ 這行用引號包起來，或改成 %23bfd6f6,%238dbdff,... 也可

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist
